Repository mapeditor/rs-tiled, pull requests merged in 2022-02, with the labels that each got.

#150 Add layer tint color; Fix `Color` parsing issues
  CHANGELOG.md
  assets/tiled_image_layers.tmx
  src/layers.rs
  src/properties.rs
  tests/lib.rs
Labels: bug, enhancement, breaking

#152 Better errors
  src/error.rs
  src/layers/tile/util.rs
  src/map.rs
  src/properties.rs
Labels: enhancement, breaking

#133 Add SFML example
  .github/workflows/rust.yml
  CONTRIBUTORS.md
  Cargo.toml
  examples/sfml/main.rs
  examples/sfml/mesh.rs
  examples/sfml/tilesheet.rs
Labels: help wanted

#154 Hotfix: Fix CI
  .github/workflows/rust.yml
Labels: bug

#156 Changed Rc<Tileset> to Arc<Tileset>
  examples/sfml/tilesheet.rs
  src/cache.rs
  src/map.rs
  temp
Labels: enhancement, breaking

#153 Simplify internals
  src/animation.rs
  src/layers/tile/util.rs
  src/objects.rs
  src/tile.rs
  src/tileset.rs
  src/util.rs
Labels: enhancement

#157 Refactor chunk system
  examples/main.rs
  examples/sfml/main.rs
  src/layers/mod.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/util.rs
  tests/lib.rs
Labels: enhancement, breaking

#163 Remove `Data` types from the interface
  examples/main.rs
  examples/sfml/main.rs
  src/layers/group.rs
  src/layers/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/map.rs
  src/objects.rs
  src/tile.rs
  src/util.rs
  tests/lib.rs
Labels: enhancement, breaking

#160 Make path a requirement for parsing tilesets
  src/error.rs
  src/map.rs
  src/tile.rs
  src/tileset.rs
Labels: enhancement, breaking

#172 Wrap `Tile` over a data type
  src/layers/tile/mod.rs
  src/tile.rs
  src/tileset.rs
  tests/lib.rs
Labels: enhancement, breaking
