Repository mapeditor/rs-tiled, pull requests merged in 2022-03, with the labels that each got.

#173 Add some missing attributes
  src/animation.rs
  src/cache.rs
  src/layers/group.rs
  src/layers/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/mod.rs
  src/lib.rs
  src/map.rs
  src/objects.rs
  src/tile.rs
  src/tileset.rs
  src/util.rs
Labels: enhancement

#174 Add preliminary documentation
  README.md
  src/animation.rs
  src/cache.rs
  src/error.rs
  src/image.rs
  src/layers/group.rs
  src/layers/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/lib.rs
  src/map.rs
  src/objects.rs
  src/properties.rs
  src/tile.rs
  src/tileset.rs
  src/util.rs
Labels: enhancement, tests

#180 Use `Color` for color property type
  assets/tiled_group_layers.tmx
  src/properties.rs
  tests/lib.rs
Labels: enhancement, breaking

#181 Fix docs and rename member
  src/error.rs
  src/properties.rs
Labels: enhancement, breaking

#184 Better macros
  src/animation.rs
  src/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/map.rs
  src/objects.rs
  src/tileset.rs
  src/util.rs
Labels: enhancement

#186 Better specification for `Image::source` + example
  assets/folder/tiled_relative_paths.tmx
  src/image.rs
Labels: enhancement, tests

#182 Implement Deref for wrapper types
  examples/main.rs
  src/image.rs
  src/layers/group.rs
  src/layers/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/lib.rs
  src/map.rs
  src/objects.rs
  src/util.rs
  tests/lib.rs
Labels: enhancement, breaking

#185 Rename `TiledError` to `Error` + Add `Result` type
  src/animation.rs
  src/cache.rs
  src/error.rs
  src/image.rs
  src/layers/group.rs
  src/layers/image.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
  src/layers/tile/util.rs
  src/map.rs
  src/objects.rs
  src/properties.rs
  src/tile.rs
  src/tileset.rs
  src/util.rs
Labels: enhancement, breaking

#188 Update changelog
  CHANGELOG.md
Labels: enhancement

#191 Implement Deref for Tile<'tileset>
  README.md
  src/layers/tile/mod.rs
  src/tile.rs
  src/tileset.rs
  tests/lib.rs
Labels: enhancement, breaking

#201 Fix iterator lifetimes
  src/layers/group.rs
  src/layers/object.rs
  src/map.rs
Labels: bug

#197 Common layer interface
  CHANGELOG.md
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/mod.rs
Labels: enhancement

#202 Improve CI; Add rustfmt & clippy jobs
  .github/workflows/rust.yml
  examples/sfml/main.rs
  examples/sfml/tilesheet.rs
  src/animation.rs
  src/error.rs
  src/image.rs
  src/layers/group.rs
  src/layers/mod.rs
  src/layers/object.rs
  src/layers/tile/finite.rs
  src/layers/tile/infinite.rs
  src/layers/tile/util.rs
  src/map.rs
  src/objects.rs
  src/parse/xml/map.rs
  src/properties.rs
  src/tileset.rs
  tests/lib.rs
Labels: enhancement
